public class CommissionCalculatorConstants {
    public static final string itemGroupTile='Tile';
    public static final string itemGroupAncillary='Ancillary';
    public static final string rectroActive='Retroactive';
    public static final string marginal='marginal';
    public static final string salesRepADProfile = 'Sales Representative - A&D';
	public static final Map<Integer,String> monthByNumber = new Map<Integer,String>{1 => 'Jan', 2 => 'Feb', 3 => 'Mar', 4 => 'Apr', 5 => 'May', 6 => 'Jun',
                                                                                    7 => 'Jul', 8 => 'Aug', 9 => 'Sep', 10 => 'Oct', 11 => 'Nov', 12 => 'Dec'};
}